### ISSUE TITLE
Design principles

### ISSUE THREAD

**Issue by hannah-ustwo** [AusDTO/gov-au-ui-kit#404] opened 2016-10-05 00:06 UTC
As a user of the Thing I need to understand the design principles so I use it to build services with the same goals/principles (may need to reword this).

**Comment by gazhands** [comment] 2016-10-17 04:52
GOV.UK 
Design Principles

Listed below are our design principles and examples of how we’ve used them so far. These build on, and add to, our original 7 digital principles.
1. Start with needs*
2. Do less
3. Design with data
4. Do the hard work to make it simple
5. Iterate. Then iterate again.
6. This is for everyone
7. Understand context
8. Build digital services, not websites
9. Be consistent, not uniform
10. Make things open: it makes things better

**Comment by joolswood** [comment] 2016-10-19 03:18
*Also our Design Principles https://www.dto.gov.au/standard/design-principles/ :)

**Comment by joolswood** [comment] 2016-10-19 03:21
WRT to dev principles, we have starting points already in the rep https://github.com/AusDTO/gov-au-ui-kit/blob/develop/BROWSER-SUPPORT.md 

```
Principles

Support basic access and functionality in the browsers and devices of all of our users.
Build a solid semantic HTML5 foundation.
Progressive enhancement over graceful degradation. Build the basic foundation for the lowest common denominator then enhance — instead of a managed degraded experience for older browsers (fault tolerance).
```

**Comment by joolswood** [comment] 2016-10-31 22:21
I've uploaded a [scan of the CALD principles doc here](https://drive.google.com/open?id=0B476d7OhSs9gZW5hZUNHQjJvN1E) I mentioned @gazhands (still trying to get hold of a digital copy). The most relevant to us is probably 1: `Use common protocols, layouts and icons to assist users to access government agencies`.

**Comment by hannah-ustwo** [comment] 2016-11-02 00:02
Clarifying that this is about overrarching high level principles for the guide, not on a component/element basis

**Comment by hannah-ustwo** [comment] 2016-11-02 00:03
@gazhands @joolswood to tackle this

**Comment by joolswood** [comment] 2016-12-13 04:22
Archiving this as duplicate of #8 in Design Guide repo

**Closed as completed** 2016-12-13 04:22 UTC
